cuda: False
cell: 'lstm'
num_layers: 3
bidirectional: True
hidden_size: 256
emb_src_size: 256
reuse_words: True
attention: 'concat'
coverage: False
pointer: False
method: 'adadelta'
max_grad_norm: 2.0
